[package]
name = "hyperlane-broadcast"
version = "0.7.4"
readme = "README.md"
edition = "2024"
authors = ["root@ltpp.vip"]
license = "MIT"
description = """hyperlane-broadcast is a lightweight and ergonomic wrapper over Tokioâ€™s broadcast channel designed for easy-to-use publish-subscribe messaging in async Rust applications. It simplifies the native Tokio broadcast API by providing a straightforward interface for broadcasting messages to multiple subscribers with minimal boilerplate."""
keywords = ["time", "hyperlane", "broadcast", "tokio", "hyperlane"]
repository = "https://github.com/crates-dev/hyperlane-broadcast.git"
categories = ["network-programming", "web-programming"]
exclude = [
    "target",
    "Cargo.lock",
    "sh",
    ".github"
]

[dependencies]
dashmap = "6.1.0"
tokio = { version = "1.47.1", features = ["full"] }
twox-hash = "2.1.1"

[profile.dev]
incremental = false
opt-level = 3
lto = true
panic = "unwind"
debug = false
codegen-units = 1
strip = "debuginfo"

[profile.release]
incremental = false
opt-level = 3
lto = true
panic = "unwind"
debug = false
codegen-units = 1
strip = "debuginfo"
